first commit requests view
EthicApp-Development/ethicapp-main pull request #242
Opened 2023-09-14 23:34 UTC by vicentegana10

2023-09-27 18:57 UTC, mabarraza commented
@vicentegana10 Porfavor agrega en el PR una breve descripción de lo realizado. Adicionalmente si son vistas  nuevas o en general cambios visuales por favor agrega fotos de los cambios para que el proceso de revisión sea más expedito e informativo para quienes vean los PR :D

2023-09-28 15:02 UTC, claudio-alvarez requested changes

2023-09-28 15:02 UTC, claudio-alvarez commented on admin-panel/src/pages/Request.js
Tengo dos comentarios:

1. Es importante que las traducciones sean consistentes. Faltan las traducciones de nombres de campos en esta vista.
2. El nombre Request para el componente es muy genérico. Podría haber otro tipo de Requests. Quizás podrías ponerle TeacherAccountRequest.

2023-09-28 15:02 UTC, claudio-alvarez commented on admin-panel/src/pages/Requests.js
- Aquí hago saltar las alarmas porque estamos viendo URLs harcodeadas. Esto tiene que provenir de una configuración, idealmente a través de variables de entorno. También podría provenir desde configuración en base de datos, pero lo primero es más eficiente, sin ser menos seguro.

2023-09-28 15:02 UTC, claudio-alvarez commented on ethicapp/app.js
Ojo con las opciones por default de CORS, pues podrían ser muy permisivas y con ello suprimir el efecto que CORS debe tener en la seguridad de la aplicación. Idealmente se deberían autorizar orígenes que quedan listados en variables de entorno o configuración de la aplicación de frontend.

2023-10-08 16:59 UTC, mabarraza requested changes
Bastante bueno por mi lado, te pediría que arregles unos pequeños temas visuales en los modulos donde se actualiza la data, que idealmente sean todos los "bloques" del mismo tamaño por temas de consistencias y no insinuar que alguno es de alguna forma más importante que el otro, adjunto foto de la diferencia:

![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/bf418578-33ff-473e-8ef1-890faa54d147)

![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/2306c079-1fb6-4264-89d0-b92f58ea4146)

2023-10-09 21:24 UTC, mabarraza commented
Perfecto, todo bien!, procedo a realizar el merge.

2023-10-09 21:24 UTC, merged