[ethicapp-v2] teacher account request api methods
EthicApp-Development/ethicapp-main pull request #246
Opened 2023-09-25 22:53 UTC by vicentegana10

2023-09-27 19:03 UTC, mabarraza commented
@vicentegana10 no olvides agregar una descripción de lo trabajado en el PR así como cualquier evidencia fotográfica que consideres necesaria.
Por otro lado cuando levantes issues y/o PRs porfavor sigue los lineamientos establecidos para mantener los diferentes issues y PRs ordenados y que su seguimiento sea más fácil y expedito, si quieres más detalles sobre dichos lineamientos puedes verlos en el readme de guidelines del proyecto, te dejo el link acontinuación: https://github.com/EthicApp-Development/organization/blob/master/Guidelines/git-workflow.md#4-pull-requests

2023-09-28 15:01 UTC, claudio-alvarez requested changes

2023-09-28 15:01 UTC, claudio-alvarez commented on ethicapp/backend/controllers/users.js
Faltan las validaciones de pre-existencia de cuenta.

- Si ya hay un usuario con rol de profesor creado con el mismo correo electrónico, error.
- Si ya hay un usuario con rol de alumno creado con el mismo correo electrónico, crear petición de _upgrade_ de cuenta. Para esto conversamos que habría que añadir una variable de estado (flag) a la tabla que determine si la petición es la de un upgrade o no (default).

2023-10-04 01:28 UTC, vicentegana10 reviewed
validaciones pre cuenta añadidas

2023-10-08 17:08 UTC, mabarraza requested changes
Veo bien los filtros agregados para revisar que no haya duplicidad de cuentas de profesor. Te pediría que porfavor remuevas los console.log() que dejaste en el código por temas de limpieza de código y de no mostrar información que no queremos mostrar en las herramientas de desarrollador.

2023-10-09 20:42 UTC, vicentegana10 reviewed
console.logs out

2023-10-09 20:55 UTC, mabarraza commented
Perfecto, procedo a realizar el merge!

2023-10-09 21:01 UTC, merged