[ethicapp-v2] Arreglo de elementos duplicados tras merge rama frontend_controllers_refactoring
EthicApp-Development/ethicapp-main pull request #254
Opened 2023-10-07 17:08 UTC by javiersoto99

Para esta solución se arreglo la vista duplicada del alumno y la vista de forgot-pass.ejs.

Además se agregaron estos cambios por lado de la visualidad y funcionamiento:
 

- Confirmacion para terminar una actividad:
![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/cc88d0bf-93ba-452f-9bbe-a320fc8c975b)

- Cuando se este viendo una actividad terminada no se muestras los botones de siguiente y terminar, ya que pueden provocar un bug en la actividad:
![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/eec54206-c0cc-4b00-b04d-eca58c852a50)

- Arreglos visuales al chat del alumno en actividad de ranking, para que sea mas notorio el tab y siguiendo la paleta de colores:
![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/807201d6-3bf4-42d5-9ce9-7e5225650872)

2023-10-08 15:40 UTC, mabarraza requested changes
Estan bien buenos los cambiso visuales y se agradece el arreglo de los elementos duplicados que se me pasaron en el merge. 

Por otro lado, @javiersoto99  te pediría que al nuevo pop-up de confirmación de término de una actividad le agregues la traducción en inglés correspondiente (Are you sure you want to end the activity?). Adicionalmente y a esto le puede dar el victo bueno @claudio-alvarez te pediría  que aparezca al centro de la pantalla y que se opaque el background para dar a entender de la forma más demostrativa posible que se tiene que confirmar si efectivamente se quiere terminar la actividad.

2023-10-09 19:37 UTC, claudio-alvarez commented
> Estan bien buenos los cambiso visuales y se agradece el arreglo de los elementos duplicados que se me pasaron en el merge.
> 
> Por otro lado, @javiersoto99 te pediría que al nuevo pop-up de confirmación de término de una actividad le agregues la traducción en inglés correspondiente (Are you sure you want to end the activity?). Adicionalmente y a esto le puede dar el victo bueno @claudio-alvarez te pediría que aparezca al centro de la pantalla y que se opaque el background para dar a entender de la forma más demostrativa posible que se tiene que confirmar si efectivamente se quiere terminar la actividad.

Usamos modales (de Bootstrap) para información y confirmación. El diálogo que tenemos ahora tiene marcado "Aceptar" por default. Creo que con el modal de bootstrap la prevención es algo mejor porque no hay opción por default marcada.

2023-10-09 19:44 UTC, mabarraza commented
> > Estan bien buenos los cambiso visuales y se agradece el arreglo de los elementos duplicados que se me pasaron en el merge.
> > Por otro lado, @javiersoto99 te pediría que al nuevo pop-up de confirmación de término de una actividad le agregues la traducción en inglés correspondiente (Are you sure you want to end the activity?). Adicionalmente y a esto le puede dar el victo bueno @claudio-alvarez te pediría que aparezca al centro de la pantalla y que se opaque el background para dar a entender de la forma más demostrativa posible que se tiene que confirmar si efectivamente se quiere terminar la actividad.
> 
> Usamos modales (de Bootstrap) para información y confirmación. El diálogo que tenemos ahora tiene marcado "Aceptar" por default. Creo que con el modal de bootstrap se da una experiencia más consistente, y además la prevención de una selección accidental es algo mejor porque no hay opción por default marcada.

Entiendo, en ese caso procederé a hacer el merge

2023-10-09 19:47 UTC, javiersoto99 commented
> Entiendo, en ese caso procederé a hacer el merge
Según entiendo tengo que actualizar el modal de confirmación, ya que actualmente se tiene un window.alert y @claudio-alvarez esta proponiendo crear un modal con Bootstrap. Después de esto se puede hacer el merge o no?

2023-10-09 19:48 UTC, mabarraza commented
> > Entiendo, en ese caso procederé a hacer el merge
> 
> Según entiendo tengo que actualizar el modal de confirmación, ya que actualmente se tiene un window.alert y @claudio-alvarez esta proponiendo crear un modal con Bootstrap. Después de esto se puede hacer el merge o no?

Efectivamente, yo entendí mal, ya eliminé mi anterior comentario

2023-10-09 20:27 UTC, javiersoto99 commented
Acabo de cambiar el modal anterior a uno utilizando Bootstrap, acá dejo las imágenes de como se ve.

En español:
![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/192747af-f3e7-49a2-ac37-cd3b17d44923)

En inglés:
![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/6e8494da-a092-4dcf-94bd-97a8e6b10ebe)

Estaré atento a cualquier cambio que sea necesario.

2023-10-09 20:41 UTC, mabarraza commented
> Acabo de cambiar el modal anterior a uno utilizando Bootstrap, acá dejo las imágenes de como se ve.
> 
> En español: ![image](https://user-images.githubusercontent.com/62267638/273690865-192747af-f3e7-49a2-ac37-cd3b17d44923.png)
> 
> En inglés: ![image](https://user-images.githubusercontent.com/62267638/273690953-6e8494da-a092-4dcf-94bd-97a8e6b10ebe.png)
> 
> Estaré atento a cualquier cambio que sea necesario.

Buenísimo, quedó bueno bueno, ahora sí procederé a realizar el merge!

2023-10-09 20:41 UTC, merged