[Admin-Panel] Actualización de base de datos y registro de evento.
EthicApp-Development/ethicapp-main pull request #261
Opened 2023-10-11 14:19 UTC by jigracia

En este PR se agregan nuevas tablas en la base de datos con el propósito de generación de reportes en la vista de administrador. También se modifican los docker compose para que el admin panel se lance en conjunto con las otras aplicaciones.

2023-10-11 14:34 UTC, claudio-alvarez requested changes
Habría que:

- Poner ojo con el naming de atributos en SQL, usamos snake case.
- Resolver el despliegue de la aplicación React desde el path admin/

2023-10-11 14:34 UTC, claudio-alvarez commented on postgres-db/schema/create_38.sql
Ojo con el naming de la variable isProfessor, usamos snake case en SQL. Tendría que ser is_professor. Incluso mejor queda llamar todo lo que es "professor" como "teacher". En inglés, el Professor es el "Profesor Titular" universitario, o sea, el profesor de más alto rango que hay.

2023-10-11 14:34 UTC, claudio-alvarez commented on web-nginx/nginx.conf
La deducción de entorno admin puede fallar si se accede a un recurso (p.ej., asset) que se llama admin. Es mejor utilizar las soluciones de cambiar el path base con que funciona el router en la aplicación React, y configurarlo para que la aplicación siempre funcione bajo /admin

2023-10-11 21:33 UTC, jigracia commented on web-nginx/nginx.conf
Solución implementada en el ultimo commit

2023-10-11 21:54 UTC, jigracia commented
Importante mencionar que la versión de producción ha de funcionar con la imagen de Ethicapp que esta en dockerhub, ósea que no es la que esta actualizada con el registro de eventos y API de generación de reportes.

2023-10-11 21:57 UTC, jigracia commented
También cabe mencionar que para acceder a la pagina de administrador a través de nginx es necesario ingresar a "http://localhost:8080/admin/. Importante que debe ser "/admin/" , no "/admin"

2023-10-11 21:58 UTC, jigracia commented on postgres-db/schema/create_38.sql
Variable arreglada y testeada en el ultimo commit.

2023-10-12 17:07 UTC, mabarraza requested changes
Veo aplicados los cambios pedidos por Claudio, bien por ese lado , lo único que te pediría es que arregles errores de tipo de diseño de código, ya que al usar tanto los linters de sql y js me encontre un buen par de errores por ahí, te adjunto fotos de los errores más abajo. Para obtener los errores de JS y SQL debes ejecutar `npm run lint-js` y `npm run lint-sql` respectivamente. Cabe mencionar que a estas alturas si bien se realizó una limpieza de este estilo el semestre pasado, a estas alturas se han pasado errores, así que en ese sentido sólo te pido que arregles los errores pertinentes al codigo creado/editado por tí.


![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/95b69f76-ceb6-4f4b-a442-edaa457dd0f0)

![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62113405/1b4d52dd-f393-4e34-a591-6b6e0ca6afb7)

2023-10-12 18:38 UTC, jigracia commented
Solución implementada en el ultimo commit

2023-10-12 19:50 UTC, merged

2023-10-12 19:50 UTC, mabarraza commented
Perfecto, muchas gracias!

2023-10-15 19:15 UTC, mabarraza reviewed
Perfecto , todo bien por mi lado, muchas gracias @jigracia