[ethicapp-v2] Issue #265: Implementación de proceso de bundling y minificación del modulo teacher-admin.mjs
EthicApp-Development/ethicapp-main pull request #266
Opened 2023-10-16 01:18 UTC by javiersoto99

Para este issue se utilizaron las herramientas de esbuild (bundle), terser (minificación) y express-asset-versions (versionamiento de los assets).

Para iniciar el proceso se tiene que ejecutar el comando `npm run bundle-teacher-module`, con esto se realiza el proceso de bundling y minificacion correspondiente y se crea un archivo nuevo llamado `bundled-teacher-admin.min.js`.

Para llamar al modulo se utiliza el middleware de express-asset-versions que según su documentación (https://www.npmjs.com/package/express-asset-versions) determina que versión de un archivo se desea ejecutar viendo si el `NODE_ENV=production` o `NODE_ENV=development`. Por ende desde el home.ejs se llama de la siguiente manera:

`<script rel="stylesheet" src="<%= asset('/js/ngmodules/teacher/teacher_admin.mjs','/js/ngmodules/teacher/bundled-teacher-admin.min.js') %>" type="module" defer></script>`

Ademas en este issue se hicieron un par de arreglos en la interfaz de profesor que indica el tipo de diseño en los tabs de actividades y diseños:
![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/117863f8-c380-486d-9b1e-f62279ad7d89)
![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/89c6860b-2aa0-45dc-b682-d0d8486063e2)

2023-10-19 13:17 UTC, claudio-alvarez requested changes
Necesitaríamos crear un sólo task de bundling que genere todo el código de producción, tanto para el teacher como para el alumno, y que pueda ser invocado como "build".

2023-10-19 13:17 UTC, claudio-alvarez commented on package.json
Pienso que podría haber un sólo task para hacer build para producción, igual que en React, que llame a todos los scripts o subtasks que sean necesarios para generar el bundle minificado de código para producción. De lo contrario, se requiere estar invocando muchas tareas en forma manual y esto puede causar errores u omisiones involuntarias al momento de hacer despliegue de la aplicación en producción.

2023-10-19 13:17 UTC, claudio-alvarez commented on package.json
Por otro lado, el .env incluye una variable de entorno llamada ETHICAPP_ENV que define si la aplicación está ejecutando en development, staging, o production. Sugiero utilizar esta variable que ya habíamos definido para que la consulte el middleware de assets. Si hubiera un impedimento duro del middleware para sólo usar NODE_ENV, entonces, podríamos analizar si cambiar ETHICAPP_ENV a NODE_ENV en el archivo .env, pero probablemente esto no sea necesario.

2023-10-21 21:53 UTC, mabarraza approved these changes
Todo bien, queda por mi parte revisar que funcione el versionamiento de assets en staging. De no ser el caso como bien comentó @claudio-alvarez se evaluará el cambio del nombre de variable ETHICAPP_ENV por NODE_ENV

2023-10-21 21:55 UTC, merged