[ethicapp-v2] Arreglos visuales en interfaz del alumno
EthicApp-Development/ethicapp-main pull request #283
Opened 2023-10-23 13:26 UTC by javiersoto99

Para este issue se restructuraron las vistas del alumno (seslist.ejs, roles.ejs y ethics.ejs). Con el fin de mejorar la visualidad general y el flujo de respuesta para el alumno. Acá se muestran los dos flujos (cada diseño tenia 2 preguntas, una pregunta sin cometario y una con comentario obligatorio):

**Ranking**

https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/761ba8be-4cb1-43a0-bad6-12018a844615

**Diferencial Semántico** 

https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/3a80ef3f-67d2-4bd7-b649-47f19d238dfd

2023-10-23 20:05 UTC, claudio-alvarez requested changes
Sólo un par de cambios en los textos de traducción.

2023-10-23 20:05 UTC, claudio-alvarez commented on ethicapp/frontend/assets/i18n/EN_US/english.json
Puedes cambiar `noDocQuestion` a `Unable to view the document?`?

2023-10-23 20:05 UTC, claudio-alvarez commented on ethicapp/frontend/assets/i18n/ES_CL/spanish.json
Ojo, en español se usa ¿ para abrir una pregunta, faltó en `noDocQuestion`.

2023-10-23 20:14 UTC, claudio-alvarez commented
Tengo un comentario respecto a desplegar el botón para ver el documento en una nueva pestaña. En primer lugar, haría este feature algo más discreto, pues su propósito es lidiar con una excepción. La prioridad que tienen el botón y la leyenda en la pantalla - encima del documento y extendiéndose por varias líneas de texto - da como para pensar que se tratara de regla (algo que todo el momento ocurre) y no de excepción.

Propongo dos soluciones:

1. Usar esta [solución de aquí](https://medium.com/@paulisache/how-to-display-a-pdf-in-an-iframe-using-filereader-api-5b0ed9239402) y [aquí](https://stackoverflow.com/questions/76114053/first-fetch-and-then-display-pdf-in-separate-browser-without-popup-warning) para cargar programáticamente el PDF. Al cargar programáticamente el PDF, se pueden manejar mejor los códigos de error, 404 o de otro tipo, y mostrarle al usuario un mensaje más claro - "Hubo un error cargando el documento [Reintentar]".
2. Simplemente, disminuir el tamaño del botón "Cargar documento en pestaña" cosa de hacerlo más discreto y ponerlo encima del iframe, reduciendo los márgenes verticales.

2023-10-23 20:42 UTC, javiersoto99 commented
Por ahora adopte la solución de sólo colocar el botón que le de la opción al alumno de abrir el documento en otra pestaña, ya que este se usa en el caso de que al alumno le moleste ver el documento haciendo recortado y tener que hacer scroll en el iframe. El resultado es el siguiente:

![image](https://github.com/EthicApp-Development/ethicapp-main/assets/62267638/8a89b905-c154-4062-a9f5-c7cc7a069214)

2023-10-24 13:01 UTC, mabarraza approved these changes
Todo bien, procedo a realizar el merge

2023-10-24 13:01 UTC, merged