[api-v2/issue-296] adicion de tablas y cambios de nombre para sequelize (#296)
EthicApp-Development/ethicapp-main pull request #301
Opened 2024-04-07 16:15 UTC by benjamin-gonzalez-diaz

2024-04-11 00:20 UTC, benjamin-gonzalez-diaz commented
en este ultimo commit, se prevé que cambie la ruta para ejecutar la seed dependendiendo del ETHICAPP_ENV dentro del archivo .env

2024-04-12 18:54 UTC, claudio-alvarez requested changes
Es necesario mejorar el código de acuerdo a las observaciones que realicé anteriormente. Fundamentalmente, "que migraciones se definan como migraciones, y modelos se definan como modelos".

2024-04-12 18:54 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/users.js
Los nombres de las clases son en PascalCase.

2024-04-12 18:54 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/usersessionsreport.js
El nombre de la tabla debería ser user_session_reports, pues el modelo es UserSessionReport

2024-04-12 18:54 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/addcolumnsconstraints.js
Me llama la atención que AddColumnsAndConstraint sea un _modelo_.

2024-04-12 18:54 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/sessionquestionstext.js
¿Cómo tendría que ser el nombre del modelo?
Alternativa 1: SessionQuestionText
Alternativa 2: SessionQuestionTexts
Otra? 

El nombre de tabla session_question_texts (plural de SessionQuestion) sería el apropiado.

2024-04-12 18:54 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/addcolumnstotables.js
Encuentro extraño usar modelos para crear tablas y agregar las columnas, y que de hecho haya un modelo llamado "addcolumnstotables". ¿No debería realizarse esto a través de migraciones?

2024-04-12 18:54 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240331190812-designs.js
1. Hagamos que los archivos de migración hagan una sola operación de creación o modificación, y que los nombres de los archivos de migración describan lo que la migración hace. Ojo: si se define en una migración creación de una tabla, incorporar en la _misma_ migración la definición de las restricciones de integridad referencial (claves foráneas), y otro tipo de restricciones de integridad post creación de las columnas (p.ej., not null, nullable, etc.).
2. No generemos modelos para hacer lo que una migración tiene que hacer (modificar el schema relacional).
3. Utilicemos correctamente las convenciones de case para nombres de modelos, tablas, columnas, etc.
4. Recordar que el nombre de una migración (nombre del archivo) debe _indicar lo que la migración hace_.

Dejo una conversación con GPT sobre cómo usar el generador de modelos de sequelize-cli para ir creando modelos y migraciones, juntos y por separado:

https://chat.openai.com/share/c7183873-b4c6-4228-9279-0730c085ca1c

2024-04-22 13:34 UTC, claudio-alvarez requested changes
Modelos van en PascalCase y singular. Las tablas de base de datos en plural y en snake_case.

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240413213457-create-teamusers.js
Esta es una tabla de unión entre users y teams. Debería llamarse teams_users.

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240413213953-1°_constraints_and_add_columns.js
Evitemos caracteres especiales en los nombres de archivo. En este caso, el símbolo de grado, podría causar algún problema, pues no es un símbolo comúnmente utilizado en nombres de archivo.

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240414013213-create-jigsaw-users.js
> +      user__id: {
aquí no tienes choque de nombres, pienso que user_id a secas debería funcionar.

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/actors.js
> +  class actors extends Model {
Las clases de modelo, van con PascalCase, y en singular.

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/actors_selections.js
> +  class actors_selections extends Model {
El modelo sería ActorSelection

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/designs.js
> +  class designs extends Model {
Design

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/designs_documents.js
> +  class designs_documents extends Model {
DesignDocument

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/differential_chat.js
> +  class differential_chat extends Model {
SDChatMessage

El prefijo SD es de SemanticDiferential.

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/differentials.js
>  module.exports = (sequelize, DataTypes) => {
SemanticDifferentialItem

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/differentials.js
> +  class differentials extends Model {
Estamos considerando usar una sola tabla Questions para guardar todo tipo de preguntas en forma no estructurada (JSONB). Esta tabla (y modelo) tendrían que morir.

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/differentials_selections.js
Análogo a lo anterior. Este modelo tendría que llamarse SDResponse (Semantic Differential Response). Pero ya habíamos diseñado un modelo/tabla Response (responses), que pudiera guardar respuestas en formato no estructurado (jsonb) a fin de evitar la multiplicidad de tablas requeridas si lo hacemos estructurado.

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/documents.js
> +  class documents extends Model {
Document

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/finished_sessions.js
> +  class finished_sessions extends Model {
Es raro mantener un modelo para sesiones finalizadas. En vez de un modelo, debería bastar un enum en la tabla/modelo sessions (Session) con todos los códigos de estado posibles, incluyendo aquel que informa que una sesión está finalizada.

Eliminaría este modelo y me enfocaría en investigar la manera de crear un enum asociado a sessions que nos permita mantener el estado de sesiones sin usar números mágicos o una multiplicidad de flags booleanos.

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/jigsaw_roles.js
> +  class jigsaw_roles extends Model {
JigsawRole

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/jigsaw_users.js
> +  class jigsaw_users extends Model {
Este modelo debería ser JigsawUserRole

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/questions.js
Me consta que esta es la tabla que queríamos para guardar preguntas en formato no estructurado (jsonb), y así poder tener todas las preguntas en una sola tabla. Hagámosla consistente con lo antes diseñado.

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/sessions_questions_texts.js
¿Qué objetivo tendría esta tabla si ya estamos definiendo questions/Question, que por cada pregunta contendría toda la información pertinente?

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/sessions_status.js
SessionStatus

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/stages.js
> +  class stages extends Model {
Stage

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/teams.js
> +  class teams extends Model {
Team

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/teamusers.js
La tabla referida es puramente de unión. Si las consultas funcionan similar a ActiveRecord, probablemente no se requiere el modelo "TeamUser".

2024-04-22 13:34 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/users_sessions_reports.js
> +  class users_sessions_reports extends Model {
UserSessionReport

2024-04-22 13:41 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/sessions_status.js
El estado de sesión podría darse en una columna de sessions, usando una enum:

https://chat.openai.com/share/89b0cfe5-1907-4a64-963c-b810d44661f8

2024-05-16 14:18 UTC, claudio-alvarez requested changes
Necesitamos continuar perfeccionando nombres de modelos y tablas para cumplir convenciones.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/oldModels/actors_selections.js
> +  class Actor_selection extends Model {
ActorSelection, recordemos que clases van en PascalCase.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/messages.js
> +  class Messages extends Model {
Optemos por nombrarlo ChatMessage para darle una connotación más específica. No olvidemos que nombres de modelos van en singular.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/responses.js
> +  class responses extends Model {
Esta debería ser Response.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240422210635-create-responses.js
> +      responses: {
Debería llamarse "content" este campo, para reflejar que se trata del contenido de una respuesta, que tiene formato de objeto.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240422210635-create-responses.js
> +    await queryInterface.createTable('responses', {
Las columnas relevantes para esta tabla tendrían que ser:

id
user_id (quien crea la response)
content (jsonb, contenido)
type (string descriptor del tipo de objeto de respuesta; así podemos identificar si se trata de una respuesta, por ejemplo, de "diferencial semántico", o de ranking, etc.).
createdAt
updatedAt

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240422210635-create-responses.js
> +      uses: {
Esta columna no me queda claro para que sería.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/messages.js
> +    modelName: 'messages',
ojo que usaríamos chat_messages y ChatMessage como par tabla-modelo.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/questions.js
> +  class Questions extends Model {
Question, en singular.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/questions.js
>      sesion_id: DataTypes.INTEGER,
debería ser stage_id en vez de session_id, pues question va asociada con una stage (más específico que una session)

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240413213457-create-teamusers.js
> +    await queryInterface.createTable('team_Users', {
Es una tabla de unión que sirve para unir teams con users. En este caso, la convención es que van los nombres de ambas tablas separadas por un guión bajo:

teams_users

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/documents.js
>      modelName: 'documents',
Ojo con modelName, tiene que llevar el nombre de la clase, en este caso Document

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/jigsaw_users.js
>      modelName: 'jigsawUsers',
Ojo, mejor sacar el modelName y que se infiera automáticamente respecto al nombre de la clase.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/oldModels/sessions_status.js
>      modelName: 'sessionsStatus',
Mejor sacar modelName.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240413215343-create-users-sessions-reports.js
> +    await queryInterface.createTable('User_Sessions_Reports', {
Cuando son tablas de base de datos, va todo en minúscula y en snake_case¡.
sería user_session_reports, así si luego hubiera que especificar un modelo, sería UserSessionReport

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240413202902-create-sessions-users.js
> +    await queryInterface.createTable('sessions_Users', {
sería sessions_users como tabla de unión entre sessions y users

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240414012950-create-jigsaw-roles.js
> +    await queryInterface.createTable('jigsaws_roles', {
Esta no me parece que sea una tabla de unión, más bien, es una tabla que describe el rol que se utiliza en una actividad de tipo jigsaw.
El nombre tendría que ser:

jigsaw_roles

y un modelo relacionado tendría que llamarse JigsawRole

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/migrations/20240414013213-create-jigsaw-users.js
> +    await queryInterface.createTable('jigsaws_users', {
jigsaw_users
JigsawUsers

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/teachersaccountsrequests.js
> +    modelName: 'teachers_accounts_requests',
teacher_account_requests

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/designs_documents.js
> +    tableName: 'designs_documents'
¿Es una tabla de unión? ¿o es un Modelo realmente que sirve para representar los documentos adjuntos a un diseño?
Si es un modelo, la tabla tendría que llamarse design_documents (plural de design_document - DesignDocument).

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/jigsaw_roles.js
> +    tableName: 'jigsaws_roles'
Esto sería jigsaw_roles

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/messages.js
> +    tableName: 'messages'
chat_messages

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/report_activity.js
> +    modelName: 'report_activity',//class
ActivityReport
activity_reports

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/report_create_account.js
> +    modelName: 'report_create_account',//class
AccountCreationReport
account_creation_reports

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/report_login.js
> +    modelName: 'report_login',//class
LoginReport
login_reports

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/report_type.js
> +    modelName: 'report_type',//class
ReportType
report_types

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/responses.js
> +    modelName: 'Responses',//class
Response
responses

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/sessions.js
> +  class Sessions extends Model {
Debería ser Session, en singular, pues es nombre de un modelo, ojo.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/sessions.js
> +  Sessions.init({
Session

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/sessions.js
> +    modelName: 'Sessions', //class
Session
sessions

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/sessions_users.js
>      sesion_id: DataTypes.INTEGER,
ojo, session_id

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/sessions_users.js
> +    tableName: 'sessions_Users',
SessionsUsers - ojo que es una tabla de unión, por lo que el modelo puede no ser necesario

La tabla se tiene que llamar sessions_users, es decir, en snake_case, sin ninguna letra mayúscula.

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/teachersaccountsrequests.js
> +    tableName: 'teachers_accounts_requests', //Table
TeacherAccountRequest
teacher_account_requests

2024-05-16 14:18 UTC, claudio-alvarez commented on ethicapp/backend/controllers/api/v2/models/users_sessions_reports.js
> +    tableName: 'user_sessions_reports' //Table
UserSessionReport
user_session_reports

2024-05-24 13:16 UTC, claudio-alvarez approved these changes

2024-05-24 13:17 UTC, claudio-alvarez approved these changes

2024-05-24 13:18 UTC, claudio-alvarez reviewed
Par de detalles menores respecto a nombres.

2024-05-24 13:18 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/index.js
>  app.use('/',activiyRouter);
activityRouter, ojo.

2024-05-24 13:18 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/index.js
> +app.use('/',questionsRouter);
pongámosle questionRouter, debido a que todos los demás archivos están nombrados en singular.

2024-05-24 13:19 UTC, claudio-alvarez reviewed
Está todo bien aquí.

2024-05-24 13:20 UTC, claudio-alvarez reviewed
Me ha parecido bien todo esto.

2024-05-24 13:25 UTC, claudio-alvarez approved these changes
Quedan resueltos los detalles encontrados.

2024-05-24 13:25 UTC, merged