Issue 291
EthicApp-Development/ethicapp-main pull request #306
Opened 2024-04-22 18:34 UTC by sdiazgt

Este Pull Request contiene el progreso de 3 diferentes issues: el issue #303, #290 y #291.

# Issue 303
Se implementó nuevas variables de ambiente dentro del archivo ".env" y "docker-compose.yml". Remplazando variables harcoded dentó del archivo Visor.js y content-analysis/app.js, relacionadas con Puertos y direcciones Host.

# Issue 290
Se implementa ruta de callback, con las siguientes características añadidas para su funcionamiento:
- Se agrega validación de conexión a partir de una Api validation key, agregando un método de validar un mensaje por parte del servicio content-analysis a las diferentes rutas de Ethicapp.
- Se agrega tabla content-analysis, para almacenar la respuesta correspondiente al servicio content-analysis. Permitiendo realizar un UPSERT dentro de la tabla.

# Issue 291
Se implenta llamada de Socket "contentUpdate", la cual permite emitir un mensaje con el resultado del servicio content-analysis hacia la vista de actividades del profesor, manejando la respuesta dentro del controlador DashboardController. Este último parsea la data dentro del Scope, almacenando el resultado usando el número del stage y id de pregunta como llaves.

2024-05-03 18:15 UTC, claudio-alvarez requested changes
Proceder de acuerdo a las observaciones.

2024-05-03 18:15 UTC, claudio-alvarez commented on .env
> +NODE_HOST_NAME=node
Te quedaría mejor algo como ETHICAPP_HOSTNAME, pues puede existir por ahí otro servicio que usa node por abajo

2024-05-03 18:15 UTC, claudio-alvarez commented on .env
> +CONTENT_ANALYSIS_HOST_NAME=content-analysis
Me llama la atención la mezcla de kebab-case y PascalCase en los nombres de hosts. Creo que kebab-case funciona mejor para nombres de hosts.

2024-05-03 18:15 UTC, claudio-alvarez commented on docker-compose.yml
> +      API_VALIDATION_KEY: ${API_VALIDATION_KEY}
¿No debería ser simplemente API_KEY? Incluso podría quedar como ETHICAPP_API_KEY

2024-06-09 02:44 UTC, sdiazgt commented
Por problemas con Rebase squash, se creó una nueva branch con los commits reducidos correspondientes a este PR. Se creará un nuevo PR dedicado al los issues #290 y #291. Se cerrará el PR una vez creado el nuevo PR.

2024-06-09 08:12 UTC, sdiazgt commented
El nuevo PR de este issue es el #336.

2024-06-09 08:12 UTC, closed without merging