[api-v2/issue-321]  creacion de varios test  #321 & #322
EthicApp-Development/ethicapp-main pull request #323
Opened 2024-05-25 22:21 UTC by benjamin-gonzalez-diaz

para este pull request se crearon test para probar la creacion de nuevos usuarios, la autenticacion al hacer login, la creacion de sessiones y la incorporacion de usuarios a la session

esto se hicieron creando archivos .test.js para probarlo

2024-05-31 13:09 UTC, claudio-alvarez requested changes

2024-05-31 13:09 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/register-user.js
> +router.get('/users', async (req, res) => {
Esto debería ser solamente accesible por un admin, de lo contrario, es completamente inseguro... cualquier usuario registrado como alumno literalmente se roba la base de datos con todos los users.

Por otro lado, podríamos averiguar para un endpoint como este (index con potencialmente muchos objetos), ver si existe forma de ir cargando los datos por lotes (en batches). Es decir, para obtener todos los datos, tener que hacer llamadas sucesivas.

2024-05-31 13:13 UTC, claudio-alvarez requested changes

2024-05-31 13:13 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/register-user.js
> +router.get('/register/users', async (req, res) => {
Tener rutas /register hace sentido si la aplicación estuviera sirviendo páginas y uno quisiera acceder a una página de registro con GET /register, pero es una aplicación de tipo API con la que manipulamos los objetos (recursos) directamente, entonces, basta con dejar las rutas con /users e implementar las operaciones contra ese path.

2024-05-31 13:16 UTC, claudio-alvarez requested changes
Lo único que me hizo un poco de ruido es ese objeto de user mock declarado inline en donde no se ve que haya un campo de password_confirmation. ¿Cuál es el propósito de se mock user siendo que están éstos definidos en otro archivo separado (user.json)?

2024-05-31 13:16 UTC, claudio-alvarez commented on ethicapp/test/unit/userRegistration.test.js
> +            pass: '$2a$10$...',
Mi duda aquí es por qué password_confirmation no está...

2024-05-31 13:18 UTC, claudio-alvarez approved these changes
Me ha parecido bien todo esto aquí.

2024-05-31 13:19 UTC, claudio-alvarez approved these changes
Me ha parecido bien implementado este test de acuerdo a la especificación del requisito.

2024-05-31 13:19 UTC, claudio-alvarez approved these changes
Esto me ha parecido bien.

2024-05-31 13:31 UTC, claudio-alvarez requested changes
El cambio más importante sería cómo quedan definidos todos los paths de endpoints según la versión de la API, lo cual habría que hacer definiendo una variable en un módulo, e interpolando dicha variable en todos los paths de rutas de endpoints según la versión de la API.

2024-05-31 13:31 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/sessions-users.js
> +// Create session user
Adds a user to the session

2024-05-31 13:31 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/sessions-users.js
> +router.get('/sessions/:sessionId/users', async (req, res) => {
Esto sólo lo debería poder llamar un usuario con permisos de admin.
Si quisiéramos dar acceso a profe, podemos hacerlo, pero tenemos que asegurar que el profe sea el creador de la sesión (control de acceso).

2024-05-31 13:31 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/sessions.js
> +router.get('/api-v2/sessions/:id/users', authenticateToken, async (req, res) => {
Esto se me había pasado y ahora me llamó mucho la atención. Todos los paths de API deberían comenzar con /api/v2/. Deberíamos definir una variable de prefijo, por ejemplo, API_VERSION_PATH_PREFIX, que contenga este string, "/api/v2", y para cada ruta, usar, por ejemplo, `${API_VERSION_PATH_PREFIX}/users/:id` en caso que fuera GET (show) de un user.

Además, ojo, la definición de esa variable debería estar en un módulo que sea incluido desde todos los archivos que definen rutas para la versión de la API específica.

En un futuro quisiéramos, por ejemplo, implementar la versión 2.1 de la API. En este caso, crearíamos otro módulo con la variable API_VERSION_PATH_PREFIX seteada para esa versión, e incluiríamos el módulo en todos los controladores en archivos definidos bajo el path /api/v2.1

2024-05-31 13:32 UTC, claudio-alvarez approved these changes

2024-05-31 13:35 UTC, claudio-alvarez requested changes
Me parece que falta probar el intento de acceso de un usuario a una sesión usando un código no válido.

2024-06-14 13:48 UTC, claudio-alvarez requested changes
Necesitamos implementar control de acceso en endpoints mutativos, para verificar que el usuario pueda realizar acciones mutativas sólo sobre recursos de los que es dueño (caso de profesores y alumnos), o todos los recursos (admin).

2024-06-14 13:48 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/phases.js
> +router.delete('/phases/:id', async (req, res) => {
En operaciones mutativas necesitamos siempre verificar que el usuario tenga el rol adecuado y además sea el dueño del recurso. Aquí no estamos verificando al usuario, entonces cualquier usuario autenticado de la API puede mutar recursos de otros usuarios!

2024-06-14 13:48 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/phases.js
> +router.put('/phases/:id', async (req, res) => {
En operaciones mutativas necesitamos siempre verificar que el usuario tenga el rol adecuado y además sea el dueño del recurso. Aquí no estamos verificando al usuario, entonces cualquier usuario autenticado de la API puede mutar recursos de otros usuarios!

2024-06-14 13:48 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/phases.js
> +  const { number, type, anon, chat, prev_ans, activity_id } = req.body;
En operaciones mutativas necesitamos siempre verificar que el usuario tenga el rol adecuado y además sea el dueño del recurso. Aquí no estamos verificando al usuario, entonces cualquier usuario autenticado de la API puede mutar recursos de otros usuarios!

Chequear al usuario y verificar que sea dueño son operaciones que vamos a tener que implementar en forma recurrente. Esto huele a módulo especializado que podríamos implementar y consumir en todos los endpoints que hagan operaciones mutativas.

2024-06-14 13:48 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/phases.js
> +  const { number, type, anon, chat, prev_ans, activity_id } = req.body;
Es muy recomendable incorporar una solución como CASL, ya que permite implementar control de acceso definiendo granularmente las capacidades de cada usuario, y limitando la realización de acciones mutativas a recursos propios.

https://chatgpt.com/share/d670daf9-0ae1-49e4-8bf8-d7cbabfa71d5

2024-06-16 21:00 UTC, benjamin-gonzalez-diaz commented
los ultimos 3 comentarios se subieron a la rama issue-325.

2024-06-18 22:24 UTC, merged