[ethicapp-v2-ca] Implementación de interacciones entre backend de EthicApp y servicio de análisis de contenido #290, #291
EthicApp-Development/ethicapp-main pull request #336
Opened 2024-06-09 08:09 UTC by sdiazgt

Este Pull Request contiene el desarrollo dedicado a los issues #290 y #291. Este PR contiene un rebase de los commits originales.
OJO: Una vez aceptado el PR se debera eliminar la rama original "issue-291", la cual ya no se encuentra en uso.

2024-06-10 14:10 UTC, claudio-alvarez approved these changes
Apruebo estas contribuciones. @sdiazgt, sólo diría que es muy importante que en tu documento de memoria describas con el mayor detalle posible la estructura del objeto de work unit. Además, esto podría ser incorporado a un documento markdown enfocado en describir el servicio que has implementado.

2024-06-10 14:11 UTC, claudio-alvarez approved these changes
Apruebo estas contribuciones.

2024-06-10 14:16 UTC, claudio-alvarez approved these changes
Apruebo estas contribuciones.

2024-06-10 14:18 UTC, claudio-alvarez approved these changes
Apruebo estas contribuciones.

2024-06-10 14:23 UTC, claudio-alvarez requested changes
Se requieren algunos cambios menores.

2024-06-10 14:23 UTC, claudio-alvarez commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
> +                console.log("Datos no coinciden con la sesión actual:");
Podrías usar console.warn y el mensaje dejarlo en inglés.

2024-06-10 14:23 UTC, claudio-alvarez commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
>                  console.log("Datos coinciden con la sesión actual:", data);
Déjalo en inglés y con console.debug

2024-06-10 14:23 UTC, claudio-alvarez commented on ethicapp/frontend/views/partials/teacher/activity.html
> +                        <h2>Rubrica</h2>
¿Le puedes aplicar la internacionalización que tiene el resto de la vista? Tendrías que agregar los strings que estás usando a las tablas EN/ES.

2024-06-10 14:23 UTC, claudio-alvarez commented on ethicapp/frontend/views/partials/teacher/activity.html
> +                                    <th>Top</th>
Se me ocurre que la tabla debería tener un título en thead que se extienda por dos columnas, y que diga "Responses selected by relevance" / "Respuestas según relevancia"

Mayor Relevancia / Most Relevant

2024-06-10 14:23 UTC, claudio-alvarez commented on ethicapp/frontend/views/partials/teacher/activity.html
> +                                    <th>Worst</th>
Menor Relevancia / Least Relevant

2024-06-10 14:43 UTC, claudio-alvarez commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
> +                console.log("Datos no coinciden con la sesión actual:");
Me pareció ver que esto quedó resuelto en otro PR con commits más recientes.  @sdiazgt favor verificar y confirmar.

2024-06-10 14:43 UTC, claudio-alvarez commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
>                  console.log("Datos coinciden con la sesión actual:", data);
Me pareció ver que esto quedó resuelto en otro PR con commits más recientes.  @sdiazgt favor verificar y confirmar.

2024-06-10 14:43 UTC, claudio-alvarez commented on ethicapp/frontend/views/partials/teacher/activity.html
> +                        <h2>Rubrica</h2>
Me pareció ver que esto quedó resuelto en otro PR con commits más recientes.  @sdiazgt favor verificar y confirmar.

2024-06-10 14:44 UTC, claudio-alvarez commented on ethicapp/frontend/views/partials/teacher/activity.html
> +                                    <th>Top</th>
Me pareció ver que esto quedó resuelto en otro PR con commits más recientes.  @sdiazgt favor verificar y confirmar.

2024-06-10 14:44 UTC, claudio-alvarez commented on ethicapp/frontend/views/partials/teacher/activity.html
> +                                    <th>Worst</th>
Me pareció ver que esto quedó resuelto en otro PR con commits más recientes.  @sdiazgt favor verificar y confirmar.

2024-06-12 15:17 UTC, nicolasgebauer requested changes
Faltan los cambios solicitados por @claudio-alvarez por favor revisar.

2024-06-13 03:31 UTC, sdiazgt commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
>                  console.log("Datos coinciden con la sesión actual:", data);
Parte de los console.log ya se encontraban eliminados y se optó por eliminar aquellos que fueron agregados sin objetivo.

2024-06-13 03:31 UTC, sdiazgt commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
> +                console.log("Datos no coinciden con la sesión actual:");
Parte de los console.log ya se encontraban eliminados y se optó por eliminar aquellos que fueron agregados sin objetivo.

2024-06-13 03:34 UTC, sdiazgt commented on ethicapp/frontend/views/partials/teacher/activity.html
> +                        <h2>Rubrica</h2>
Un translate fue agregado un un PR posterior

2024-06-13 03:36 UTC, sdiazgt commented on ethicapp/frontend/views/partials/teacher/activity.html
> +                                    <th>Top</th>
Se agregaron los nombres sugeridos con un translate en un PR posterior.

2024-06-13 03:36 UTC, sdiazgt commented on ethicapp/frontend/views/partials/teacher/activity.html
> +                                    <th>Worst</th>
Se agregaron los nombres sugeridos con un translate en un PR posterior.

2024-06-13 03:42 UTC, sdiazgt commented
Se revisaron los cambios y se modificaron, estos cambios se podrán ver efectuados en el issue #343. @claudio-alvarez se encuentra listo para realizar merge.

2024-06-14 15:40 UTC, merged