[ethicapp-v2-ca] Implementación de vista con selecciones de contenido en dashboard de monitoreo de actividad #308
EthicApp-Development/ethicapp-main pull request #337
Opened 2024-06-09 08:11 UTC by sdiazgt

Este Pull Request contiene el desarrollo dedicado a al issue #308. Este PR contiene un rebase de los commits originales.
OJO: Una vez aceptado el PR se debera eliminar la rama original "issue-308", la cual ya no se encuentra en uso.

2024-06-10 14:11 UTC, claudio-alvarez approved these changes

2024-06-10 14:33 UTC, claudio-alvarez requested changes

2024-06-10 14:33 UTC, claudio-alvarez commented on ethicapp/backend/controllers/visor.js
> +        console.error('Error al procesar el callback:', error);
Traducir el mensaje de error a inglés.

2024-06-10 14:35 UTC, claudio-alvarez approved these changes

2024-06-10 14:35 UTC, claudio-alvarez approved these changes

2024-06-12 15:10 UTC, nicolasgebauer approved these changes

2024-06-13 03:45 UTC, sdiazgt commented on ethicapp/backend/controllers/visor.js
> +        console.error('Error al procesar el callback:', error);
El mensaje fue modificado a inglés en un PR posterior.

2024-06-13 03:47 UTC, sdiazgt commented
Se revisaron los comentarios y el PR se encuentra listo para realizar un merge @claudio-alvarez.

2024-06-14 15:40 UTC, merged