[ethicapp-v2-ca] Adiccion activación selectiva del análisis de contenido #318
EthicApp-Development/ethicapp-main pull request #338
Opened 2024-06-09 08:15 UTC by sdiazgt

Este Pull Request contiene el desarrollo dedicado a al issue #318. Este PR contiene un rebase de los commits originales.
OJO: Una vez aceptado el PR se debera eliminar la rama original "issue-318", la cual ya no se encuentra en uso.

2024-06-10 14:24 UTC, claudio-alvarez requested changes
Cambios al uso de logger.

2024-06-10 14:24 UTC, claudio-alvarez commented on ethicapp/backend/controllers/visor.js
> +        console.error('Error al procesar el callback:', error);
console.error y en inglés.

2024-06-10 14:24 UTC, claudio-alvarez approved these changes

2024-06-10 14:25 UTC, claudio-alvarez approved these changes

2024-06-10 14:26 UTC, claudio-alvarez commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
>                  console.log("Datos coinciden con la sesión actual:", data);
Usar console.debug y mensaje en inglés.

2024-06-10 14:26 UTC, claudio-alvarez commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
> +                console.log("Datos no coinciden con la sesión actual:");
Usar console.warn y mensaje en inglés.

2024-06-10 14:27 UTC, claudio-alvarez requested changes

2024-06-10 14:27 UTC, claudio-alvarez commented on ethicapp/backend/controllers/visor.js
>          console.error('Error al procesar el callback:', error);
console.error y mensaje en inglés.

2024-06-10 14:27 UTC, claudio-alvarez approved these changes

2024-06-10 14:28 UTC, claudio-alvarez approved these changes

2024-06-10 14:30 UTC, claudio-alvarez requested changes

2024-06-10 14:30 UTC, claudio-alvarez commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
>          console.log(self.shared);
Usar console.debug y dar formato adecuado (indicar módulo/endpoint que genera el mensaje). Si ya no fuera necesario este log, entonces, eliminarlo.

2024-06-10 14:31 UTC, claudio-alvarez approved these changes
Muy bien, están implementadas aquí las traducciones. Sólo pienso que podríamos cambiar "Mejores" y "Peores" por "Más Relevantes" y "Menos Relevantes" y ponerle un título indicando "Selección automática de respuestas" / "Automatic response selection"

2024-06-10 14:32 UTC, claudio-alvarez approved these changes

2024-06-12 15:01 UTC, nicolasgebauer approved these changes

2024-06-13 03:48 UTC, sdiazgt commented on ethicapp/backend/controllers/visor.js
> +        console.error('Error al procesar el callback:', error);
El mensaje fue cambiado a ingles en un PR posterior.

2024-06-13 03:49 UTC, sdiazgt commented on ethicapp/backend/controllers/visor.js
>          console.error('Error al procesar el callback:', error);
El mensaje fue cambiado a ingles en un PR posterior.

2024-06-13 03:50 UTC, sdiazgt commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
> +                console.log("Datos no coinciden con la sesión actual:");
Se optó por eliminar los mensajes sin un objetivo.

2024-06-13 03:50 UTC, sdiazgt commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
>          console.log(self.shared);
Se optó por eliminar los mensajes sin un objetivo.

2024-06-13 03:51 UTC, sdiazgt commented on ethicapp/frontend/assets/js/controllers/teacher/dashboard_controller.js
>                  console.log("Datos coinciden con la sesión actual:", data);
Se optó por eliminar los mensajes sin un objetivo.

2024-06-13 03:52 UTC, sdiazgt commented
Se revisaron los cambios y se encuentra listo el PR para un merge @claudio-alvarez.

2024-06-14 15:41 UTC, merged