[api-v2] Issue #369: Scripts de testing y configuración de base de datos de prueba.
EthicApp-Development/ethicapp-main pull request #370
Opened 2024-09-25 23:29 UTC by francisco-delamaza

- Se agregaron scripts para ejecutar tests y migraciones, además de funciones para truncar, limpiar, aplicar migraciones y poblar la base de datos de testing.
- Se configuró el entorno de testing para funcionar con una base de datos separada, incluyendo la creación de la base de datos de testing (`ethicapp_test`), su esquema, y la ejecución de seeds y migraciones.

2024-09-26 18:11 UTC, claudio-alvarez requested changes
Sólo habría dos cambios menores que hacer:

- El .env.test, cosa de dejar el .env con los defaults para desarrollo
- El docker-compose.test.yml - con la configuración para correr tests con la aplicación contenerizada.

2024-09-26 18:11 UTC, claudio-alvarez commented on .env
Te pediría dejar el .env como .env.test dado que en condiciones normales el .env debiera ser el desarrollo.

2024-09-26 18:11 UTC, claudio-alvarez commented on docker-compose.yml
El problema con la configuración con variables de desarrollo y test a la vez es que el .env va a tener solamente las variables utilizadas para desarrollo y no las variables utilizadas para testing. Entonces, convendría crear docker-compose.test.yml que permite ejecutar la configuración para correr tests. Pones todas las variables de entorno de testing en este archivo de configuración de docker-compose.

2024-09-27 15:39 UTC, francisco-delamaza commented
Se añadieron los archivos .env.test y docker-compose.test.yml con las variables de configuración necesarias para el entorno de testing. Además, se eliminaron las variables que no eran necesarias para este entorno.

Para levantar el entorno de testing se utiliza ```docker-compose --env-file .env.test -f docker-compose.test.yml up --build --detach```

2024-10-02 15:46 UTC, claudio-alvarez requested changes
Todo bien, salvo el nombre de la base de datos para development en configuración de sequelize. La base de datos de ethicapp no puede llamarse postgres, tiene que llamarse ethicapp_development.

2024-10-02 15:46 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/config/config.json
> +    "database": "postgres",
El nombre de la database no puede ser postgres, debería ser ethicapp_development para el caso del ambiente de development.

2024-10-02 15:46 UTC, claudio-alvarez commented on ethicapp/backend/api/v2/test/repeat-test.sh
Buena idea hacer esto.

2024-10-02 15:46 UTC, claudio-alvarez commented on ethicapp/package.json
Muy bien esto, quedan todas las operaciones a la mano.

2024-10-02 15:46 UTC, claudio-alvarez commented on package.json
Bien. Llama la atención que estas dependencias no hayan sido incorporadas antes.

2025-04-09 14:35 UTC, merged